;Mondial database: http://www.informatik.uni-freiburg.de/~dbis/

INSERT INTO country VALUES ('Albania','AL');
INSERT INTO country VALUES ('Greece','GR');
INSERT INTO country VALUES ('Macedonia','MK');
INSERT INTO country VALUES ('Serbia and Montenegro','YU');
INSERT INTO country VALUES ('Andorra','AND');
INSERT INTO country VALUES ('France','F');
INSERT INTO country VALUES ('Spain','E');
INSERT INTO country VALUES ('Austria','A');
INSERT INTO country VALUES ('Czech Republic','CZ');
INSERT INTO country VALUES ('Germany','D');
INSERT INTO country VALUES ('Hungary','H');
INSERT INTO country VALUES ('Italy','I');
INSERT INTO country VALUES ('Liechtenstein','FL');
INSERT INTO country VALUES ('Slovakia','SK');
INSERT INTO country VALUES ('Slovenia','SLO');
INSERT INTO country VALUES ('Switzerland','CH');
INSERT INTO country VALUES ('Belarus','BY');
INSERT INTO country VALUES ('Latvia','LV');
INSERT INTO country VALUES ('Lithuania','LT');
INSERT INTO country VALUES ('Poland','PL');
INSERT INTO country VALUES ('Ukraine','UA');
INSERT INTO country VALUES ('Russia','R');
INSERT INTO country VALUES ('Belgium','B');
INSERT INTO country VALUES ('Luxembourg','L');
INSERT INTO country VALUES ('Netherlands','NL');
INSERT INTO country VALUES ('Bosnia and Herzegovina','BIH');
INSERT INTO country VALUES ('Croatia','HR');
INSERT INTO country VALUES ('Bulgaria','BG');
INSERT INTO country VALUES ('Romania','RO');
INSERT INTO country VALUES ('Turkey','TR');
INSERT INTO country VALUES ('Denmark','DK');
INSERT INTO country VALUES ('Estonia','EW');
INSERT INTO country VALUES ('Finland','SF');
INSERT INTO country VALUES ('Norway','N');
INSERT INTO country VALUES ('Sweden','S');
INSERT INTO country VALUES ('Monaco','MC');
INSERT INTO country VALUES ('Holy See','V');
INSERT INTO country VALUES ('Iceland','IS');
INSERT INTO country VALUES ('Ireland','IRL');
INSERT INTO country VALUES ('San Marino','RSM');
INSERT INTO country VALUES ('Malta','M');
INSERT INTO country VALUES ('Moldova','MD');
INSERT INTO country VALUES ('Portugal','P');
INSERT INTO country VALUES ('United Kingdom','GB');
INSERT INTO country VALUES ('Afghanistan','AFG');
INSERT INTO country VALUES ('China','TJ');
INSERT INTO country VALUES ('Iran','IR');
INSERT INTO country VALUES ('Pakistan','PK');
INSERT INTO country VALUES ('Tajikistan','TAD');
INSERT INTO country VALUES ('Turkmenistan','TM');
INSERT INTO country VALUES ('Uzbekistan','UZB');
INSERT INTO country VALUES ('Armenia','ARM');
INSERT INTO country VALUES ('Georgia','GE');
INSERT INTO country VALUES ('Azerbaijan','AZ');
INSERT INTO country VALUES ('Bahrain','BRN');
INSERT INTO country VALUES ('Bangladesh','BD');
INSERT INTO country VALUES ('Burma','MYA');
INSERT INTO country VALUES ('India','IND');
INSERT INTO country VALUES ('Bhutan','BHT');
INSERT INTO country VALUES ('Brunei','BRU');
INSERT INTO country VALUES ('Malaysia','MAL');
INSERT INTO country VALUES ('Laos','LAO');
INSERT INTO country VALUES ('Thailand','THA');
INSERT INTO country VALUES ('Cambodia','K');
INSERT INTO country VALUES ('Vietnam','VN');
INSERT INTO country VALUES ('Kazakstan','KAZ');
INSERT INTO country VALUES ('North Korea','NOK');
INSERT INTO country VALUES ('Kyrgyzstan','KGZ');
INSERT INTO country VALUES ('Mongolia','MNG');
INSERT INTO country VALUES ('Nepal','NEP');
INSERT INTO country VALUES ('Cyprus','CY');
INSERT INTO country VALUES ('Israel','IL');
INSERT INTO country VALUES ('Egypt','ET');
INSERT INTO country VALUES ('Indonesia');
INSERT INTO country VALUES ('Papua New Guinea','PNG');
INSERT INTO country VALUES ('Iraq','IRQ');
INSERT INTO country VALUES ('Jordan','JOR');
INSERT INTO country VALUES ('Kuwait','KWT');
INSERT INTO country VALUES ('Saudi Arabia','SA');
INSERT INTO country VALUES ('Syria','SYR');
INSERT INTO country VALUES ('Lebanon','RL');
INSERT INTO country VALUES ('Japan','J');
INSERT INTO country VALUES ('South Korea','ROK');
INSERT INTO country VALUES ('Maldives','MV');
INSERT INTO country VALUES ('Oman','OM');
INSERT INTO country VALUES ('United Arab Emirates','UAE');
INSERT INTO country VALUES ('Yemen','YE');
INSERT INTO country VALUES ('Philippines','RP');
INSERT INTO country VALUES ('Qatar','Q');
INSERT INTO country VALUES ('Singapore','SGP');
INSERT INTO country VALUES ('Sri Lanka','CL');
INSERT INTO country VALUES ('Taiwan','RC');
INSERT INTO country VALUES ('Antigua and Barbuda','AG');
INSERT INTO country VALUES ('Bahamas','BS');
INSERT INTO country VALUES ('Barbados','BDS');
INSERT INTO country VALUES ('Belize','BZ');
INSERT INTO country VALUES ('Guatemala','GCA');
INSERT INTO country VALUES ('Mexico','MEX');
INSERT INTO country VALUES ('Canada','CDN');
INSERT INTO country VALUES ('United States','USA');
INSERT INTO country VALUES ('Costa Rica','CR');
INSERT INTO country VALUES ('Nicaragua','NIC');
INSERT INTO country VALUES ('Panama','PA');
INSERT INTO country VALUES ('Cuba','C');
INSERT INTO country VALUES ('Dominica','WD');
INSERT INTO country VALUES ('Dominican Republic','DOM');
INSERT INTO country VALUES ('Haiti','RH');
INSERT INTO country VALUES ('El Salvador','ES');
INSERT INTO country VALUES ('Honduras','HCA');
INSERT INTO country VALUES ('Grenada','WG');
INSERT INTO country VALUES ('Jamaica','JA');
INSERT INTO country VALUES ('Colombia','CO');
INSERT INTO country VALUES ('Saint Kitts and Nevis','KN');
INSERT INTO country VALUES ('Saint Lucia','WL');
INSERT INTO country VALUES ('Saint Vincent and the Grenadines','WV');
INSERT INTO country VALUES ('Trinidad and Tobago','TT');
INSERT INTO country VALUES ('Australia','AUS');
INSERT INTO country VALUES ('Fiji','FJI');
INSERT INTO country VALUES ('Kiribati','KIR');
INSERT INTO country VALUES ('Marshall Islands','MH');
INSERT INTO country VALUES ('Micronesia','FSM');
INSERT INTO country VALUES ('Nauru','NAU');
INSERT INTO country VALUES ('New Caledonia','NCA');
INSERT INTO country VALUES ('New Zealand','NZ');
INSERT INTO country VALUES ('Palau','PAL');
INSERT INTO country VALUES ('Solomon Islands','SLB');
INSERT INTO country VALUES ('Tonga','TO');
INSERT INTO country VALUES ('Tuvalu','TUV');
INSERT INTO country VALUES ('Vanuatu','VU');
INSERT INTO country VALUES ('Western Samoa','WS');
INSERT INTO country VALUES ('Argentina','RA');
INSERT INTO country VALUES ('Bolivia','BOL');
INSERT INTO country VALUES ('Brazil','BR');
INSERT INTO country VALUES ('Chile','RCH');
INSERT INTO country VALUES ('Paraguay','PY');
INSERT INTO country VALUES ('Uruguay','ROU');
INSERT INTO country VALUES ('Peru','PE');
INSERT INTO country VALUES ('French Guiana','FGU');
INSERT INTO country VALUES ('Guyana','GUY');
INSERT INTO country VALUES ('Suriname','SME');
INSERT INTO country VALUES ('Venezuela','YV');
INSERT INTO country VALUES ('Ecuador','EC');
INSERT INTO country VALUES ('Algeria','DZ');
INSERT INTO country VALUES ('Libya','LAR');
INSERT INTO country VALUES ('Mali','RMM');
INSERT INTO country VALUES ('Mauritania','RIM');
INSERT INTO country VALUES ('Morocco','MA');
INSERT INTO country VALUES ('Niger','RN');
INSERT INTO country VALUES ('Tunisia','TN');
INSERT INTO country VALUES ('Western Sahara','WSA');
INSERT INTO country VALUES ('Angola','ANG');
INSERT INTO country VALUES ('Congo','RCB');
INSERT INTO country VALUES ('Namibia','NAM');
INSERT INTO country VALUES ('Zaire','ZRE');
INSERT INTO country VALUES ('Zambia','Z');
INSERT INTO country VALUES ('Benin','BEN');
INSERT INTO country VALUES ('Burkina Faso','BF');
INSERT INTO country VALUES ('Nigeria','WAN');
INSERT INTO country VALUES ('Togo','RT');
INSERT INTO country VALUES ('Botswana','RB');
INSERT INTO country VALUES ('South Africa','RSA');
INSERT INTO country VALUES ('Zimbabwe','ZW');
INSERT INTO country VALUES ('Cote dIvoire','CI');
INSERT INTO country VALUES ('Ghana','GH');
INSERT INTO country VALUES ('Burundi','BI');
INSERT INTO country VALUES ('Rwanda','RWA');
INSERT INTO country VALUES ('Tanzania','EAT');
INSERT INTO country VALUES ('Cameroon','CAM');
INSERT INTO country VALUES ('Central African Republic','RCA');
INSERT INTO country VALUES ('Chad','TCH');
INSERT INTO country VALUES ('Equatorial Guinea','GQ');
INSERT INTO country VALUES ('Gabon','G');
INSERT INTO country VALUES ('Cape Verde','CV');
INSERT INTO country VALUES ('Sudan','SUD');
INSERT INTO country VALUES ('Comoros','COM');
INSERT INTO country VALUES ('Guinea','RG');
INSERT INTO country VALUES ('Liberia','LB');
INSERT INTO country VALUES ('Djibouti','DJI');
INSERT INTO country VALUES ('Eritrea','ER');
INSERT INTO country VALUES ('Ethiopia','ETH');
INSERT INTO country VALUES ('Somalia','SP');
INSERT INTO country VALUES ('Kenya','EAK');
INSERT INTO country VALUES ('Gambia','WAG');
INSERT INTO country VALUES ('Senegal','SN');
INSERT INTO country VALUES ('Guinea-Bissau','GNB');
INSERT INTO country VALUES ('Sierra Leone','WAL');
INSERT INTO country VALUES ('Uganda','EAU');
INSERT INTO country VALUES ('Lesotho','LS');
INSERT INTO country VALUES ('Madagascar','RM');
INSERT INTO country VALUES ('Malawi','MW');
INSERT INTO country VALUES ('Mozambique','MOC');
INSERT INTO country VALUES ('Mauritius','MS');
INSERT INTO country VALUES ('Swaziland','SD');
INSERT INTO country VALUES ('Sao Tome and Principe','STP');
INSERT INTO country VALUES ('Seychelles','SY');
